### ISSUE TITLE
train with continuous node feature

### ISSUE THREAD

**Issue by yusuke0324** [xinyangATK/GraphBetaDiffusion#6]
Hi @xinyangATK,

I'm currently training a model on a custom dataset where node features consist of both continuous values and multi-categorical attributes (represented as multi-hot vectors).

From my understanding, when using continuous features, the `get_logit_beta_stats_con` function should be used instead of `get_logit_beta_stats` in the precondition module.

However, I noticed that the implementation of the expected value of _logit(z_t)_ in the code seems to differ from the equation described in the paper (Appendix B, Eq. (29)). Specifically, the current code uses:

```
E1 = 1.0 / (eta * alpha_t * xmin) * (
    (eta * alpha_t * xmax).lgamma() - (eta * alpha_t * xmin).lgamma())
Shouldn't the denominator be eta * alpha_t * (xmax - xmin) instead of eta * alpha_t * xmin?
```
It seems that E2, V1, and V2 may have the same issue as well.

After applying this correction, I observed that the values in X within sample_batch start to diverge with each iteration, and the model eventually returns NaNs.
I suspect this may be related to the behavior of `get_logit_beta_stats_con`, or possibly how `scale_shift`, `sigmoid_start`, `sigmoid_end`, and `sigmoid_power` are defined.

Could you kindly advise on this?

**Comment by anastasiiakim** [comment]
Also interested in this. @yusuke0324 Did you manage to solve it?

**Comment by yusuke0324** [comment]
I ended up not using precondition and it still successfully worked.
Currently working on trying to clamp min max after precondition to prevent the issue.

**Comment by xinyangATK** [comment]
Hi @yusuke0324 ,

Thank you very much for your attention. You're absolutely right, the denominator should be `eta * alpha_t * (xmax - xmin)`. Since I didn't use the continuous precondition function in original version, I didn't have too many checks. Really thanks for telling us this issue, I will update the right function.

However, the updated continuous precondition function works well for my project. I also suspect that some hpyerparameters cause the NaNs in your case, could you mind share the scale / shape of your custom data and your own hpyerparameters? I'll try to have a look.

btw, please looking forward our new project about beta diffusion, the precondition function maybe drop in the new model which will be easy to apply beta diffusion.

**Comment by yusuke0324** [comment]
Thank you for your testing.  The following setting is used for my train. It seems like the mean is going to be negative value and std to under 1 as t increases, then input value becomes larger than 64 bits.
```
dataset:
    name: 'x'
    remove_h: null
    datadir: 'data/rplan/'
    rand_perm: False
    feat:
        type:
            - deg
            - eig1
            - eig2
        scale: 10
        norm: True
    use_small_dataset: False

general:
    name: 'x-graph-tf-model'
    forward_visualization: False
    sample_visualization: False
    vis_number: 10
    wandb: 'online'
    wandb_project: 'graphgen'
    gpus: [0, ]
    resume: null
    test_only:
    check_val_every_n_epochs: 50
    sample_every_val: 1
    val_check_interval: null
    samples_to_generate: 200
    samples_to_save: 20
    chains_to_save: 1
    log_every_steps: 50
    number_chain_steps: 50
    final_model_samples_to_generate: 300
    final_model_samples_to_save: 20
    final_model_chains_to_save: 20
    evaluate_all_checkpoints: False

train:
    n_epochs: 2000
    batch_size: 128
    lr: 0.001
    clip_grad: 1.0
    save_model: True
    num_workers: 12
    ema_decay: 0.999
    progress_bar: false
    weight_decay: 1e-12
    optimizer: adamw
    seed: 0

model:
    type: 'discrete'
    transition: 'marginal'
    model: 'graph_tf'
    diffusion_steps: 1000
    n_layers: 6
    eta_from: 'train'
    extra_features:
    high_order: False
    hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}
    hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}
    lambda_train: [5, 0]
    sigmoid_start: 10
    sigmoid_end: -13
    sigmoid_power: 1.
    scale_shift:
        node: [0.9, 0.09]
        edge: [0.9, 0.09]
    eta:
        node: [1000, 100, 100, 1]
        edge: [1000, 100, 100, 1]
    input_space: 'logit'
    pre_condition: True
    noise_feat_type: 'x'
    default_min_max: [-1., 1.]
    max_feat_num: [52, 16, 1]
    cibcentration_m: False
    concentration_strategy: 'deg'
    use_alignment_loss: true
    alignment_sigma: 0.01
    alignment_threshold: 0.05
    alignment_gamma: 3
    lambda_max_manhattan: 5.0
    lambda_max_colinear: 0.5
    lambda_max_orthogonal: 0.5

hydra:
  job:
    chdir: True
  run:
    dir: ./outputs/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}

```
